ktor:
  application:
    modules:
      - dev.sunriseydy.acgn.server.base.plugins.ApplicationKt.module
  deployment:
    port: 9390
    host: 127.0.0.1
  development: true

config:
  db:
    postgresql:
      host: "$SY_POSTGRESQL_HOST:localhost"
      port: "$SY_POSGRESQL_PORT:5432"
      database: "$SY_POSTGRESQL_DATABASE:sy_acgn"
      user: "$SY_POSTGRESQL_USER:sy_acgn"
      password: "$SY_POSTGRESQL_PASSWORD:sy_acgn"
  ANIME:
    TmdbApiKey: "$?SY_TMDB_API_KEY"
    QbApiBaseUrl: "$?SY_QB_API_BASE_URL"
    QbUserName: "$?SY_QB_USER_NAME"
    QbPassword: "$?SY_QB_PASSWORD"
    BgmUserAgent: "$?SY_BGM_USER_AGENT"