ktor:
    application:
        modules:
            - dev.sunriseydy.acgn.ApplicationKt.module
    deployment:
        port: 9390
    development: true

acgn:
    postgres:
        url: "jdbc:postgresql://localhost:5432/sy_acgn"
        user: "sy_acgn"
        password: "sy_acgn"
