### rss xml
# @no-log
GET http://localhost:9390/resources/rss/rss.xml

### home
# @no-log
GET http://localhost:9390/api
Accept: application/json

### error
# @no-log
GET http://localhost:9390/api/error
Accept: application/json

### get localizations
# @no-log
GET http://localhost:9390/api/common/localizations
Accept: application/json

### create rss
# @no-log
POST http://localhost:9390/api/anime/rss
Accept: application/json
Content-Type: application/json

{
  "link": "http://localhost:9390/resources/rss/rss.xml"
}

### get rss list
# @no-log
GET http://localhost:9390/api/anime/rss
Accept: application/json

### delete rss
# @no-log
DELETE http://localhost:9390/api/anime/rss/7
Accept: application/json

### fetch rss
# @no-log
PUT http://localhost:9390/api/anime/rss/fetch
Accept: application/json

### get rss items
# @no-log
GET http://localhost:9390/api/anime/rss/item?rssId=1&isRead=true
Accept: application/json

### mark rss item as read
# @no-log
PUT http://localhost:9390/api/anime/rss/item/read?rssId=1
Accept: application/json