# @no-log
# @no-cookie-jar
### home
GET http://localhost:9390/api
Accept: application/json

### create rss
# @no-log
POST http://localhost:9390/api/anime/rss
Accept: application/json
Content-Type: application/json

{
  "link": "http://localhost:3000/rss.xml"
}

### get rss list
# @no-log
GET http://localhost:9390/api/anime/rss
Accept: application/json

### delete rss
# @no-log
DELETE http://localhost:9390/api/anime/rss/6
Accept: application/json

### fetch rss
# @no-log
PUT http://localhost:9390/api/anime/rss/fetch
Accept: application/json

### get rss items
# @no-log
GET http://localhost:9390/api/anime/rss/item?rssId=7&isRead=true
Accept: application/json

### mark rss item as read
# @no-log
PUT http://localhost:9390/api/anime/rss/item/read?id=b34916b7-c3d4-46e9-941e-a081486eb0f1
Accept: application/json